# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: historico.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fhistorico.proto\"%\n\x0fPedidoHistorico\x12\x12\n\nquantidade\x18\x01 \x01(\x05\" \n\x10PedidoUtilizador\x12\x0c\n\x04nome\x18\x01 \x01(\t\"B\n\x08Mensagem\x12\x11\n\tremetente\x18\x01 \x01(\t\x12\x10\n\x08\x63onteudo\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\"1\n\x11RespostaHistorico\x12\x1c\n\tmensagens\x18\x01 \x03(\x0b\x32\t.Mensagem2\x89\x01\n\x10HistoricoService\x12\x37\n\x0f\x42uscarHistorico\x12\x10.PedidoHistorico\x1a\x12.RespostaHistorico\x12<\n\x13\x42uscarPorUtilizador\x12\x11.PedidoUtilizador\x1a\x12.RespostaHistoricob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'historico_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PEDIDOHISTORICO']._serialized_start=19
  _globals['_PEDIDOHISTORICO']._serialized_end=56
  _globals['_PEDIDOUTILIZADOR']._serialized_start=58
  _globals['_PEDIDOUTILIZADOR']._serialized_end=90
  _globals['_MENSAGEM']._serialized_start=92
  _globals['_MENSAGEM']._serialized_end=158
  _globals['_RESPOSTAHISTORICO']._serialized_start=160
  _globals['_RESPOSTAHISTORICO']._serialized_end=209
  _globals['_HISTORICOSERVICE']._serialized_start=212
  _globals['_HISTORICOSERVICE']._serialized_end=349
# @@protoc_insertion_point(module_scope)
