# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import historico_pb2 as historico__pb2


class HistoricoServiceStub(object):
    """Definição do serviço gRPC para busca de histórico
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BuscarHistorico = channel.unary_unary(
                '/HistoricoService/BuscarHistorico',
                request_serializer=historico__pb2.PedidoHistorico.SerializeToString,
                response_deserializer=historico__pb2.RespostaHistorico.FromString,
                )
        self.BuscarPorUtilizador = channel.unary_unary(
                '/HistoricoService/BuscarPorUtilizador',
                request_serializer=historico__pb2.PedidoUtilizador.SerializeToString,
                response_deserializer=historico__pb2.RespostaHistorico.FromString,
                )


class HistoricoServiceServicer(object):
    """Definição do serviço gRPC para busca de histórico
    """

    def BuscarHistorico(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuscarPorUtilizador(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HistoricoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BuscarHistorico': grpc.unary_unary_rpc_method_handler(
                    servicer.BuscarHistorico,
                    request_deserializer=historico__pb2.PedidoHistorico.FromString,
                    response_serializer=historico__pb2.RespostaHistorico.SerializeToString,
            ),
            'BuscarPorUtilizador': grpc.unary_unary_rpc_method_handler(
                    servicer.BuscarPorUtilizador,
                    request_deserializer=historico__pb2.PedidoUtilizador.FromString,
                    response_serializer=historico__pb2.RespostaHistorico.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'HistoricoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class HistoricoService(object):
    """Definição do serviço gRPC para busca de histórico
    """

    @staticmethod
    def BuscarHistorico(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/HistoricoService/BuscarHistorico',
            historico__pb2.PedidoHistorico.SerializeToString,
            historico__pb2.RespostaHistorico.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BuscarPorUtilizador(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/HistoricoService/BuscarPorUtilizador',
            historico__pb2.PedidoUtilizador.SerializeToString,
            historico__pb2.RespostaHistorico.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
